# wrangler.toml
# Этот файл должен быть в корне вашего репозитория

name = "emacser" # Используйте имя вашего сервиса
main = "src/index.js" # Оставьте эту строку для формальности, но Worker будет игнорировать ее, если есть [site]

compatibility_date = "2025-11-15" # Установите текущую или более позднюю дату

[site]
# Ключевая настройка: Wrangler будет знать, что нужно брать статику
# из папки _site, которую создал Jekyll.
bucket = "_site" 

# Следующая строка говорит Wrangler, где искать Worker-скрипт, 
# который обслуживает вашу статику. Обычно он генерируется Wrangler.
entry-point = "workers-site"
